lang: "pt_BR"
ssl: true
title: "Questionando"
description: "O seu banco de questões gratuíto"
author: "Eduardo Oliveira (@EduardoJM)"
baseurl: ""
url: "https://questionando-se.github.io/biologia"
github_url: "https://github.com/questionando-se/biologia"
subject: "Biologia"
iconType: "material"
icon: "landscape"